# Generated by Django 5.2.8 on 2025-11-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=50)),
                ('pontos', models.IntegerField(default=0)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
